### ISSUE TITLE
Vulnarability in axios

### ISSUE THREAD

**Issue by Mwandia** [tawn33y/africastalking-ts#16]
Axios version 0.19.2 has a vulnarability to SSRF as described further in PR [#3410](https://github.com/axios/axios/pull/3410) on the axios repo.

### Motivation
This is a severe vulnarability, the dependabot has attempted to update the package in PR #4 but the several tests failed in the build pipelines

### Contribution
I can manually update axios package version to the lowest version that has the vulnarability patched. Also by changing some tests to handle current response formats from africastalking APIs. For example:

- Token: test 'generates auth token' expects result to contain key 'lifetimeInSeconds' but this is not part of response

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/africastalking-ts/issues/23).
